env:
  id: Discrete
  kwargs:
    w_alignment: 1.0
    w_smoothness: 0.5
    w_switch: 0.3
    w_theme: 0.3

agent:
  algo: MaskablePPO
  algo_kwargs:
    policy: MultiInputPolicy
    policy_kwargs: {}

train:
  n_envs: 8
  total_timesteps: 10000000
  n_eval_episodes: 20
  eval_freq: 100000
  save_freq: 1000000
  seed: 42
  save_path: logs/
  log_path: logs/
  device: cpu
  split_ratio: 0.9